= Научные революции и смена типов научной рациональности

Наука проходит в своём развитии три этапа: классический, неклассический и постнеклассический \cite:[kohanovskiy].

== Классическая наука

_Классическая наука_ (17-19 века) при исследовании объектов стремилась устранить всё что относится к субъекту. Такое устранение рассматривается как необходимое условие объективности знаний.

Фридрих Гегель - основоположник диалектики, жил в 1770 - 1831 гг. в Германии.



== Неклассическая наука

_Неклассическая наука_ (первая половина 20 века)  отвергает объективизм классической науки,  осмысливает связи между знаниями объекта и  деятельностью субъекта.

Карл Ясперс - основоположник экзистенциализма, жил в 1883 - 1969 гг. в Германии.

== Постнеклассическая наука

_Постнеклассическая наука_ ( вторая половина 20 начало 21 века) учитывает соотнесенность полученных знаний об объекте не только с деятельностью субъекта, но и с его ценностно-целевыми структурами.

Постнеклассические философские исследования конца XX в. ознаменовались также и выдвижением на первый план различных концепций роста и развития процесса человеческого познания и особенно научного знания \cite:[sergeeva].
