= Модель роста научного знания К. Поппера

В процессе становления наука переходила от позитивизма к неопозитивизму и постпозитивизму.

== Классический позитивизм

Огюст Конт - основоположник позитивизма, жил в 1798 - 1857 гг. в Париже.

Исторически первым целостным логико-познавательным (философским) подходом к исследованию науки был неопозитивизм (логический позитивизм), возникший в ходе научной революции начала XX века. Важнейшими темами, проблемами, над которыми задумывались неопозитивисты, были: предмет философии науки (позитивной науки), роль знаково-символических средств научного мышления, соотношение теоретического аппарата и эмпирического базиса науки, сущность и роль математизации и вообще формализации научного знания. 

Неопозитивисты развили дальше принципы, выдвинутые позитивистами XIX вв., в частности идеи родоначальника позитивизма О. Конта на сущность науки и научного познания: а) скромность претензий – опираться только на данные опыта; б) антиметафизичность – освобождение от всяких теоретических построений, в частности от философии, на том основании, что каждая наука сама себе философия cite:[obidina].

При этом схема гипотетико-дедуктивного метода, который был главным у логических позитивистов, была следующая: законы физики выступают первоначальными гипотезами об устройстве мира. Затем из этих гипотез с помощью логики, математических уравнений выводятся частные следствия, которые затем находят эмпирическую _проверяемость_. 

Более четко идея отделения научных высказываний от ненаучных, примата эмпирических знаний над теоретическими прозвучала в следующих критериях, принципах научности, предложенных неопозитивистами: 

1) принцип верификации – научным является такое суждение, которое может быть проверено опытом или сведено к логико-математическому высказыванию. То есть верификация идей – это проверка их на истинность посредством подтверждения фактами; 

2) принцип физикализма – научными являются суждения, объясняемые законами физики, ибо язык физики – универсальный язык науки; 

3) принцип конвенционализма – в основе естественнонаучных теорий лежат произвольные соглашения (конвенции) между учеными, базирующиеся на соображениях удобства, целесообразности в выборе того или иного понятийного аппарата. 

Данные положения составили основу так называемой «стандартной позитивистской модели познания», в которой имели место попытки понимания _роста научного знания_ на основе чистого языка наблюдения, выведения одних утверждений науки из других на основе правил логики, дистанцирования эмпирического уровня от теоретического, проведение демаркационной (различительной) линии между научными и ненаучными утверждениями и концепциями.

== Постпозитивизм К. Поппера

Однако, начиная с 50-х гг. XX столетия, логический позитивизм вступает в период кризиса. Причем кризис наступил не столько из-за внешней критики, сколько осознания внутренней недостаточности и неадекватности. Логика реального развития знания указывала на то, что ни один пункт программы логических позитивистов не выполняется: нет жесткой разделительной линии между аналитическими и синтетическими высказываниями, контекст обоснования знаний связан с контекстом открытия, протокольные предложения, выражающие «чистый» чувственный опыт субъекта, на самом деле очень сильно субъективно окрашены и теоретически нагружены, в связи с этим не существует незыблемого эмпирического базиса. В результате в 60-е годы XX столетия направленность философских воззрений на науку начинает меняться. Возникает _постпозитивизм_ – историческое направление в западной философии науки, отходящее от ориентации на исследование только формально-логических конструкций научного знания, обращающееся к истории науки, к анализу ее движущих сил.

Карл Поппер - основоположник постпозитивизма, жил в 1902 - 1994 гг. в Австрии и Великобритании.

Центральной идеей К. Поппера являтся осознание непостижимости истины и проблема роста научного знания. Научное знание прогрессирует благодаря предположениям. Эти предположения контролируются критикой, то есть попытками опровержения. Они способны выдержать эти проверки, однако их никогда нельзя признать ни безусловно истинными, ни даже «вероятными» \cite:[popper].

Идея фальсификации как критерия научности принадлежит К. Попперу. Он обратил внимание на то, что в науке процедуры подтверждения и опровержения имеют различный познавательный статус. Так, никакая последовательность подтверждений не может доказать истинность общего суждения (универсальной закономерности) \cite:[logic].

Основными темами постпозитивизма становятся вопросы: как возникают теории, каковы критерии их сравнения, как они добиваются признания и так далее. Вместо резких противопоставлений науки и философии, поспозитивисты ищут связи между составляющими науки, между наукой и философией, наукой и ненаукой. Они вводят понятие «состояние революции» в науке и нормального её развития \cite:[obidina].

Постпозитивизм отказывается видеть жёсткие границы между наукой и философией, признает осмысленность философских положений и неустранимость их из научного знания. Характерной чертой постпозитивизма является и его стремление опереться на историю науки, на развитие знания. В отличие от неопозитивизма, постпозитивизм отказывается от кумулятивизма в понимании развития знания и признает существенные, революционные преобразования, когда происходит пересмотр ранее признанного (теорий, фактов, методов) cite:[ushakova]. Поппер утверждает невозможность какого-либо предсказания или предвидения в истории, так как наблюдать можно лишь уникальные процессы. Всеобщие законы формируют положения относительно всех процессов определенного рода, но такая гипотеза не может рассчитывать на проверку.

Главным в научном процессе является не простое накопление фактов (процесс кумуляции), а эволюция знания, которая проявляет себя через ниспровержение, устранение уже существующих выводов новой научной теорией – методом проб и ошибок, через критический подход. По мнению Поппера, рост научного знания требует наличия трёх обязательных условий: научная теория должна вырасти из простой объединяющей идеи, она должна быть независимо проверяемой и должна выдержать все самые строгие проверки. Отсюда теория роста научного знания как частный случай общих эволюционных мировых процессов включает в себя решение проблемы, конструирование, критическое рассмотрение, оценку и критическую проверку. К. Поппер в своей знаменитой работе «Логика научного открытия» выдвигает тезис ограниченности научного познания наряду с игнорированием общепринятых авторитетных мнений в науке cite:[sergeeva].

Он приходит к выводу, что не может быть специфического, только философского метода, поэтому можно пользоваться в философии любыми методами. Такая позиция приводит философа к гносеологическому анархизму. Кроме того, Поппер вводит два обязательных критерия научности знания, основанных, во-первых, на тезисе фаллибилизма (учение о погрешимости знания) и, во-вторых, на принципе фальсификации (опровержение выдвинутой теории). Принцип фаллибилизма принимает истину как нечто временное, преходящее, как постоянно обновляющуюся процедуру, причем такой подход затронул даже и такие «точные» науки, как логика и математика. При подобном подходе истина в критическом рационализме Поппера становится всего лишь верой. Что касается отбора научных гипотез из огромного их множества, то здесь Поппер предлагает следовать принципу фальсификации, суть которого в том, что не может быть полной уверенности в истинности теории, так как она в любой момент может быть опровергнута любым фактом или аргументом.

Именно поэтому Поппер выдвигает как критерий научного статуса теории возможность ее фальсификации, когда научная теория крайне заинтересована в самом факте её опровержения, ведь для Поппера только истинно научные теории могут быть опровергнуты иными, более продуктивными научными концепциями. Отсюда, по мнению Поппера, идеал науки состоит в постоянном самообновлении, а критический метод и есть истинный метод науки.

== Критика постпозитивизма

Своеобразную трактовку проблемы роста и развития научного знания предложил и американский представитель философии науки П. Фейерабенд, который на вопрос о возможности достижения объективной истины только в результате процесса научного познания отвечает крайне отрицательно. Достижение объективной истины, по его мнению, невозможно именно в силу ограниченности любой теории. 

В спорной, дискуссионной, даже в некоторой степени провокационной работе «Как защитить общество от науки», он скептически оценивает огромную силу авторитета в научном познании, даже некое обожествление науки и принятие многих её положений «на веру». 

По его мнению, постулаты науки зачастую базируются не на логике и рационализме, а скорее принимаются некритически подобно религии, базирующейся на вере. Научно-логическое знание для Фейерабенда мирно сосуществует и с другими равноценными альтернативными подходами получения знания в виде мифа, религии, магии. Такой подход не позволяет свести всю гносеологию (как теорию познания) только к эпистемологии (теории научного знания). 

Антисциентизм Фейерабенда решающую роль в спорах различных методологических концепций отдает факту истории, он требует обратиться в анализе процесса «становящегося» знания к истории философии и истории науки, познанию духовного мира древних и таким образом широко использовать диалектический метод исследования наряду с учетом социальных аспектов познания и социокультурного фактора развития науки. Фейерабенд, вслед за Поппером и даже в значительно ещё большей степени, олицетворяет концепцию «гносеологического/методологического анархизма», когда ученым и исследователям в процессе получения знания не должно зацикливаться на одном лишь виде знания, а следует использовать любые подходы и методы. По Фейерабенду, само научное знание пронизано социальнополитическими, этико-религиозными и даже мифологическими предрассудками, т.е. оно такое же как и другие виды знания, не хуже и не лучше. 

Именно поэтому он акцентирует свое внимание на одном единственном принципе, который, по его мнению, «можно защищать при всех обстоятельствах и на всех этапах человеческого развития – допустимо все». Такую позицию философ выразил в своем знаменитом, не раз критикуемом тезисе «Все дозволено». 

Фейерабенд, наряду с Поппером, Куном и Лакатосом, составляя знаменитую «большую четверку» современного этапа развития философии, подводят итог идеям «критического рационализма» и способствуют построению различных «плюралистических моделей науки» в контексте социокультурного анализа получения знания.
