= Характеристики постнеклассической науки

Характерными чертами постнеклассической науки являются глобальный эволюционизм, системность и холизм cite:[chernikova].

== Глобальный эволюционизм

Глобальный эволюционизм – это интегративное исследовательское направление, учитывающее динамику развития неорганического, органического и социального миров. Он опирается на идею о единстве мироздания и представления о том, что весь мир является огромной эволюционирующей системой. 

Глобальный эволюционизм включает 4 типа эволюции: космическую, химическую, социальную, биологическую – объединяя их генетической и структурной преемственностью.

Герберт Спенсер - родоначальник эволюционизма, жил в 1820 - 1903 гг. в Великобритании.

Универсальный эволюционизм соединяет идею развития и системный подход cite:[kuznetsova]. Системная целостность развивается, дифференцируется, порождая новые состояния и перестраивая внутреннюю структуру cite:[stepin].

== Самоорганизующиеся системы

Синергетика (с древнегреч. – содействие, соучастие) – теория самоорганизации, сделавшей своим предметом выявление наиболее общих закономерностей спонтанного структурогенеза. 

Синергетика фокусирует внимание на таких ситуациях, в которых структуры или функции систем переживают драматические изменения на уровне макромасштабов. В частности, синергетику особо интересует вопрос о том, как именно подсистемы или части производят изменения, всецело обусловленные процессами самоорганизации. 

Саморазвивающиеся системы находят внутренние формы адаптации к окружающей среде. Неравновесные условия вызывают эффект корпоративного поведения элементов, которые в равновесных условиях вели себя независимо и автономно. В ситуациях отсутствия равновесия согласованность элементов системы, в значительной мере возрастает. Определенное количество или ансамбль молекул демонстрирует когерентное поведение, которое оценивается как сложное cite:[obidina].

Постнеклассическая наука исследует не только сложные, сложно организованные системы, но и сверхсложные системы, открытые и способные к самоорганизации. Согласно синергетике, в мире нет тех универсальных законов, которые делали возможным его познание в классическом смысле. Синергетика осуществляет радикальную переоценку ценностей. Она претендует на пересмотр онтологии мира, сложившейся линейной модели прогресса, кумулятивной модели знания cite:[sudas].

Для того, чтобы система могла рассматриваться, как самоорганизующаяся, она должна быть термодинамически открытой, иметь нелинейные динамические уравнения, которые значительно отклоняются от критических значений и процессы в которых происходят кооперативно cite:[kuznetsova].

== Холизм

Целое больше суммы. Свойства целого сводится к свойству его частей.

Объект понимается на основе представления о мироустройстве, которое называют эволюционный холизм, стержнем которого является эволюционно-синергетическая парадигма. Сегодня о синергетике говорят как о целостном междисциплинарном знании процессов самоорганизации систем различного субстрата. Эволюционно-синергетическая парадигма является знанием нового типа, это трансдисциплинарное знание, которое характеризуют не только как кооперацию многих научных областей, но и как перенос когнитивных схем из одной области в другую. Эволюционно-синергетическая парадигма, которую называют ещё парадигмой сложности, позволяет построить единую картину мира, в которой человек укоренён в природе, мир и человеческое бытие соразмерны и потому конструирование искусственной природы и социальных институтов осуществляется в единой сети взаимодействий cite:[chernikova].

