= Этапы развития средневековой философии: патристика и схоластика. Схоластический метод и развитие логического мышления 

== Патристика: Аврелий Августин

#Патри́стика (от греч. πατήρ [patér], лат. pater – отец) – богословская дисциплина, предметом которой является изучение, анализ и систематизация богословских воззрений Отцов Церкви, а также выдающихся церковных учителей; систематическое изложение заимствованных из отеческих творений доказательств, которые служат для исторического обоснования христианских истин.#

Во II в. возникла [.line-through]#так называемая# _патристика_ — направление христианской мысли, в котором стремились использовать достижения античной философии для защиты и обоснования христианского учения. Патристика просуществовала до VIII в., став первой ступенью в развитии философии средневековья. _Средневековая философия развивалась с V в., от крушения Римской империи до возникновения ранних форм капиталистического общества (XIV—XV вв.)_, то есть патристика являлась своеобразным переходным мостиком от античной философии к философии эпохи феодализма. Она начала своё развитие, когда ещё разрабатывались античные воззрения, и завершила его уже в рамках философии феодального общества. Особенно велико было влияние на раннюю патристику взглядов античных стоиков неоплатонических идей.

В рамках патристики решалась задача углублённой разработки вероучения и философии христианства. Отцы церкви создали обширную святоотеческую литературу, вобравшую в себя совокупность философско-теологических учений этих христианских мыслителей (теология — богословие).

Патристику подразделяют на восточную (греко-византийскую) и западную (латинскую). Наиболее крупными представителями восточной патристики были _Ориген, Дионисий Ареопагит, Иоанн Дамаскин_ и др., западной — _Аврелий Августин, Боэций_ и др. 

#*Боэций* (480-524) - римский государственный деятель. В 524 году в результате придворной интриги был обвинён в заговоре против власти и стремлении вернуть Риму утраченную свободу, заключён в тюрьму и спустя год или два казнён. В ожидании казни написал «Утешение Философией», которое стало одной из популярнейших книг Средневековья и оказало сильное влияние на европейскую литературу. Боэций — автор трудов по богословию и логике.#

*Августин* (354-430) родился в г. Тагасте в Северной Африке. Его мать была христианкой, а отец — язычником. В юности Августин беззаботно жил в Карфагене. 

Вначале Августин познакомился с одним из популярных религиозных течений своего времени — манихейством. Оно учило о дуализме мирового добра и зла и утверждало, что человеческие создания обладают двумя душами, одна из которых добрая и светлая, а другая — злая и тёмная. Но он недолго оставался сторонником манихейства. Оно не давало сил для нравственной жизни, к которой стремился Августин. Отойдя от манихейства, он примкнул к скептицизму, который также не удовлетворил его. Он обратился к <<neoplatonism,неоплатонизму>> (Плотин). Но его личный опыт пришел в конфликт с неоплатонистской верой в разум, согласно которой правильное понимание ведёт к правильным действиям. Так, Августин осознавал, что не способен вести жизнь, которая, как он знает, является правильной. В возрасте около тридцати лет он принял христианство.

Августин вернулся в Северную Африку и стал епископом. Вся дальнейшая его жизнь была посвящена Церкви. 

Августин написал много книг на латинском языке. *«Против академиков»*, где он, опровергая скептицизм, критикует своё прошлое увлечение скептицизмом. *«О свободной воле»*, где обсуждается проблема зла и свобода воли. *«Исповедь»*, где Августин, раскрывает перипетии своей духовной борьбы. В произведении *«О граде Божием»* Августин разрабатывает собственное видение истории и учение о «Двух градах» («Царствах») — Граде Земном и Граде Божием. 

Жизнь Августина пришлась на период после признания христианства доминирующей религией и раздела Римской империи, на период, непосредственно предшествовавший вторжению германских племён, которое разрушило Западную римскую империю. 

Августин оказался одним из первых великих теологов, которые связали Античность и христианское время. _Он синтезировал христианство и неоплатонизм_.

Августин утверждает, что наиболее достоверным знанием мы обладаем о внутреннем мире человека. 

Для него внутренний мир является скорее полем битвы различных чувств и побуждений воли, чем областью холодной деятельности рассудка. Внутреннее является сферой иррациональных импульсов, греха, вины и страстного желания спасения. Но в отличие от стоиков Августин не верит, что мы сами в состоянии управлять своей внутренней жизнью. Мы нуждаемся в милости и «сверхчеловеческой» помощи. 

Августин в основном разделяет неоплатонистское понимание взаимоотношения души и тела. Иначе говоря, душа представляет божественное в человеке. [.line-through]#Тело является источником греховного.# Человек должен, по возможности, [.line-through]#стать свободными от тела и# сконцентрироваться на духе, на своём внутреннем мире, чтобы приблизиться к духовному источнику существования вселенной — Богу. [.line-through]#Но как христианин# Августин к сказанному добавляет [.line-through]#и# идею первородного греха. Душа непосредственно подвержена влиянию греха.

Августин считает, что внутри каждого человека развёртывается борьба Бога и Дьявола. Он обнаруживает её и на историческом уровне в виде противостояния _Божьего града (civitas Dei) и Града земного (civitas terrena). Подобно тому, как каждая индивидуальная жизнь является полем битвы спасения и греха, так и история — полем сражения благого и греховного «царства»_.

[.line-through]#Августиновские представления о борьбе между этими двумя «царствами» были, по-видимому, навеяны современной ему политической ситуацией#. Христианство считалось причиной падения Римской империи, [.line-through]#и Августин должен был защитить его от подобных обвинений. Ещё одна интерпретация состоит в том, что, вероятно, Августин думал, хотя и никогда не выражал явно, что# Церковь [.line-through]#в определённом смысле# представляет собой Божье «царство», тогда как Империя — «царство» земное.

Однако Августин не рассматривал земное царство как случайное и не необходимое. Он считал, что из-за испорченной грехопадением природы человека сильное земное царство необходимо для обуздания зла. [.line-through]#Поэтому земное царство является необходимым злом, пока# продолжается исторический конфликт добра и зла, [.line-through]#то есть# в промежуток времени между грехопадением и Судным Днем.

В земном государстве, где существует зло, правители назначены Богом для поддержания порядка и, следовательно, не получают свою власть от народа. Правители такого государства являются богоизбранными, и народ обязан подчиняться им, поскольку он обязан подчиняться воле Бога. 

Все эти представления стали решающими для последующего времени. Церковь как организация необходима для спасения. Существующая империя — это христианское государство в том смысле, что все её члены являются одновременно подданными и императора, и папы.

_Августин объединил неоплатонизм и христианскую веру._ Согласно неоплатонизму, высшим началом мира является неизречённое, сверхсущее Единое. Единое было интерпретировано в качестве христианского Бога.

Христианство поставило людей в центр вселенной. Люди не только существуют во вселенной как более или менее высшие её создания. По большому счёту, _вселенная сотворена для человека, для его жизни и деяний в соответствии с замыслом Создателя и его законами_.

_Августин разделяет точку зрения, что именно через нашу внутреннюю жизнь мы вступаем в связь с Богом. Как духовные существа, созданные по образу и подобию Бога, мы можем с помощью веры приобщиться к Богу внутренне_. (Верующие знают о присутствии Бога в нашей внутренней жизни [.line-through]#с помощью интроспекции, как ее понимал Августин#, даже если Бог и остаётся непостижимым нашему земному разуму).

Зло не заключается в человеческом стремлении к материальному. Августин понимает моральное зло преимущественно как _неправильное использование воли_.

Воля занимает важное место в философии Августина. Она рассматривается как решающий фактор нашей духовной жизни. Конечно, разум и знание также играют свою роль, например, при выборе альтернатив, но воля обладает приоритетом над разумом.

 Августиновская трактовка воли противоположна греческой. Согласно последней, воля понималась, главным образом, как сила, предназначенная для достижения того, что разум познал в качестве блага. В общем, греки разделяли интеллектуальную концепцию человека (разум обладает приоритетом над волей), в то время как Августин придерживается волюнтаристской концепции человека (воля обладает приоритетом над разумом). 

Вначале Августин полагает, что он может приписать человеку полную свободу воли. Действия человека фундаментальным образом зависят от его собственной воли. Люди могут стремиться искать Бога и следовать Его слову, и они могут добровольно отвращаться от Бога, то есть грешить. Только в случае свободного выбора возможно говорить о грехе. Зло, таким образом, возводится к свободной воле человека, к её неправильному использованию. Другими словами, люди являются свободными и, только свободно выбрав зло, они становятся грешными. Но почему люди свободно выбирают грех? [.line-through]##Почему Бог создал людей такими, что они могут грешить по своей воле? ##

В дальнейшем Августин придерживался почти диаметрально противоположной точки зрения. Свобода воли в упомянутом выше смысле приписывается только первому человеку, Адаму. Адам обладал свободным выбором между грехом и воздержанием от греха. Но так как он свободно выбрал грех, человеческая природа стала глубоко испорченной, и это относится ко всем людям. [.line-through]##Все люди, за исключением Адама, не могут избежать греха. Выбор и свобода более не представляются существующими.##

Так как [.line-through]#все# люди [.line-through]#должны грешить и# действительно грешат, то Августин полагает, что [.line-through]#все# заслуживают вечного проклятия. Но Бог, по Его милости, позволяет [.line-through]#определённому меньшинству# избежать проклятия. [.line-through]#Так как каждый грешен, то# отбор избранных осуществляется [.line-through]#не# на основе их заслуг и достоинств. [.line-through]#Поскольку все мы в своей сущности являемся одинаково грешными, то этот отбор произволен. Подавляющее большинство будет проклято, а произвольно отобранное меньшинство будет вечно блаженствовать.#

[.line-through]##Далее Августин утверждает, что весь этот процесс в целом заранее предначертан Богом. Это является сутью августиновского учения о предопределении. Все происходящее предопределено Богом. ##

Идея [.line-through]#предопределения#, рассматриваемая с христианских позиций, должна была казаться достаточно проблематичной. [.line-through]#Если заранее решено, кто будет спасён и кто проклят, то почему тогда Бог явил своё Слово в миссии исторического Христа? Кого тогда пришел спасать Христос? Не являются ли тогда совершенно излишними основные представления христианства — воскресение Сына Божьего, все Его деяния и страдания?#

== Схоластика: Фома Аквинский

#Схола́стика (греч. σχολαστικός, лат. Scholia – «школа») – тип религиозной философии, отличающийся принципиальным подчинением примату богословского вероучения, соединением догматических предпосылок с рационалистической методикой и особым интересом к логической проблематике; получил наиболее полное развитие в средневековой Западной Европе в эпоху господства там римо-католицизма.#

Средневековую философию, часто называемую схоластикой (философией, которая «изучается в школе», по греч. schole), разделяют на три периода. 

1. _Ранняя схоластика_, которую обычно датируют временем от 400-х. гг. до 1200-х гг: _Иоанн Скот Эриугена_ (IX век), _Ансельм Кентерберийский_ (XI век), _Пьер Абеляр_ (XII век). 
2. _Зрелая схоластика_ охватывала период приблизительно с 1200 гг. до первых десятилетий XIV века: _Альберт Великий_ (ок. 1200—1280), его ученик _Фома Аквинский_ и главный оппонент Фомы _Иоанн Дуне Скот_ (1265/66-1308). 
3. _Поздняя схоластика_, характеризующая период с начала XIV века до расцвета Ренессанса. Его ведущим представителем был англичанин _Уильям Оккам_ (ок. 1300-1349/50). 

Проблема универсалий. Выражение «проблема универсалий» используется для обозначения средневековых споров вокруг вопроса о соотношении единичного и общего, о том, существует ли объективное содержание у общих понятий или нет, и если существует, то в какой форме. Основные моменты этих споров присутствовали и в дискуссии платонизма и аристотелизма и сегодня являются столь же актуальными, как и раньше. 

Обычно при анализе этой полемики используются термины _универсалия_ (общее) (лат. — _universale_) и _партикулярия_ (единичное) (лат. _particulare_). Первый обозначает общие понятия, то есть свойства («коричневый», «круглый» и т. п.) и виды («человек», «лошадь» и т. д.). Второй — отдельные вещи, то есть эту конкретную коричневую дверь, эту конкретную круглую лампу. 

Различные позиции в споре об универсалиях определяются ответами, даваемыми на вопрос о том, в каком смысле существуют универсалии. 

*Реалисты* (или концептуальные реалисты) утверждают, что универсалии являются реальными. 

*Номиналисты* полагают, что универсалии не существуют реально, а являются только именами (лат. _nomina_). 

Наряду с этими крайними позициями существуют их многочисленные варианты и промежуточные точки зрения. 

Реализм господствовал в ранней средневековой философии. В период расцвета Средневековья (ок. 1250) _Фома Аквинский представлял умеренный реализм_. Универсалии существуют в мышлении Бога (_ante res_), в единичных вещах (in rebus) и как абстракции в человеческом мышлении (_post res_). Однако в позднее Средневековье на первое место выдвинулись _номиналисты_, например, _Оккам_ и позднее — _Лютер_.

Фома Аквинский. Большинство трудов Аристотеля длительное время были неизвестны христианскому западному миру. Аристотель был впервые переоткрыт ок. 1200 гг. Первоначальная реакция церкви была негативной — Аристотель является язычником. В 1210 г. Аристотель был запрещён в Парижском университете. Но скоро этот запрет был отменен, _и учение Фомы Аквинского (1225-1274) теологически синтезировало христианство и аристотелизм_. Этот синтез оказался столь важным, что в дальнейшем Римско-католическая церковь стала рассматривать томизм (учение Фомы) как свою официальную философию. 

Фома родился вблизи местечка Аквино, недалеко от Неаполя. Он воспитывался в бенедиктинском монастыре Монте-Кассино, учился в Неапольском университете. Вопреки желанию своей семьи он стал монахом недавно созданного доминиканского ордена. В возрасте 20 лет он отправился в Парижский университет. В 1245-1248 гг. он учился у _Альберта Великого, работавшего над объединением христианства и аристотелизма_.

Жизнь Фомы была заполнена работой и путешествиями с целью обучения. Он написал удивительно большое число произведений, хотя умер незадолго до своего пятидесятилетия. Он был канонизирован в 1323 г., через 49 лет после смерти. В 1879 г. его учение было признано официальной философией Римско-католической церкви. 

Наиболее известными трудами Фомы Аквинского являются учебники по теологии _«Сумма теологии»_ и _«Сумма истины католической веры против язычников»_. Первый труд был предназначен для преподавания в школах, второй — в помощь христианским миссионерам. 

У Фомы можно встретить большинство аристотелевских идей, которые[.line-through]##, однако,## включены в христианские рамки. Фома «христианизировал» Аристотеля. [.line-through]##Аристотелевская Первопричина была заменена христианским Богом.##

Томистский синтез христианства и аристотелизма характеризуется гармонизацией — гармонизацией Бога и мира и гармонизацией веры и разума. В споре об универсалиях Фома придерживается умеренного (аристотелевского) концептуального реализма. _Понятия существуют, но только в вещах._ Наше знание начинается с чувственных восприятий, но с помощью абстракции мы распознаем общие принципы (универсалии) в вещах.

Антропология и моральная философия. Томистская антропология и моральная философия, находятся под сильным влиянием аристотелизма. В противоположность неоплатонистской традиции (например, Августину) Фома полагал, что земная и общественная жизнь так же, как тело и его функции, имеет естественное и принципиально позитивное значение. Теологически это означает, что они рассматриваются как сотворённые Богом. Фома считает, что независимо от христианского Откровения и веры люди могут познать важные аспекты творения. Точно так же он считает, что и нехристиане могут вести добродетельную жизнь в обществе и приобретать важное знание об этических нормах человеческой жизни. Бытие сотворено Богом, и люди имели способность к познанию и до Христа. 

Более того, они способны жить разумной и социальной жизнью, даже не зная Христова слова и христианского учения. 

Фома не разделяет августиновской волюнтаристской и пессимистической точки зрения на человека. 

Он следует за Аристотелем в понимании того, чем является подлинная человеческая природа. Человек по природе является разумным и духовным созданием. 

Разум обладает превосходством над волей. Мы делаем то, что разум считает добром, мы стремимся к целям, на которые нам указывает разум. 

Фома исходит из представления о всеобщих моральных нормах или законах. Существуют неизменные и общеобязательные моральные принципы. То, что люди могут по-разному понимать эти законы и принципы, доказывает не их относительность, а только то, что наша способность к их пониманию подвержена ошибкам. Сотворив нас, Бог желает добра. 

Тем не менее, Фома не думает, что для людей достаточно мирского разума и мирской способности жить по-человечески. _Высшей человеческой целью является спасение_. Но то, что нужно для спасения, выходит за пределы того, что необходимо для социально и морально приемлемой жизни. Вот почему для спасения необходимы Откровение и вера. Вера необходима для того, чтобы осветить нам цель — спасение. Вера и обращение в неё нужны для того, чтобы люди могли ими руководствоваться в своём приближении к этой наивысшей цели. 

Мораль не является независимой от религии. Согласно Фоме, даже нехристиане могут следовать правильным моральным нормам и вести подлинно моральный образ жизни. Это возможно в силу того, что они созданы Богом как обладающие разумом и способностью к рациональной и социальной жизни. Но нехристиане не смогут достичь спасения, потому что оно предполагает необходимость христианского Откровения. 

*Бог и мир*. [.line-through]#Большинство схоластов считало, что# можно рационально обосновать существование Бога. [.line-through]#Соответствующие аргументы часто называются «доказательствами существования Бога». Обсуждаемые «доказательства» имеют следующую особенность. Они утверждают, что# чувственное восприятие указывает на нечто, находящееся за его границами, и что это нечто мы можем назвать Богом.

[.line-through]#Необходимо сказать, что эти# доказательства в пользу существования Бога не являются решающими для верующего христианина. Откровения и веры достаточно для его взаимосвязи с Богом. Но такие доказательства полезны для обращения неверующих.

Рассмотрим [.line-through]#так называемый# онтологический аргумент в пользу существования Бога, который принадлежит Ансельму Кентерберийскому (1033/34-1109).

*Онтологический аргумент (Ансельм)*. В первом приближении этот аргумент состоит в следующем. Наша идея Бога — это идея о Совершенстве (о Верховном Существе). Мы не можем представить себе большего совершенства. Независимое (реальное) существование является более совершенным, чем относительное (например, вымышленное) существование. Таким образом, Бог как наивысшее Совершенство должен существовать как независимая Реальность. 

Этот онтологический аргумент подвергся критике уже при жизни Ансельма. Помимо других, в дальнейшем его критиковал Кант, который, исходя из своей философии, оспаривал любые попытки доказать или опровергнуть существование Бога. Частично критика заключалась в том, что существование Бога не может быть выведено из понятия Бога. 

Проблема зла. Если Бог является причиной всего, не является ли Он тогда и причиной зла? Рассмотрим в заключение некоторые соображения Фомы по поводу проблемы зла. 

Часть того, что люди называют злом, является необходимым следствием того, что мы живём в конечном мире. Вещи должны быть ограничены пространством и временем. Вещи не длятся бесконечно, но преходящи, в том числе и человек. [.line-through]#Эти ограничения и вытекающее из них зло необходимы даже в самом совершенном мире#. Поэтому они не могут быть приписаны воле Бога.

Далее, многое из того, что люди трактуют как зло, кажется нам таковым в силу конечности нашей позиции. Если его рассматривать с более высокой перспективы, то это кажущееся зло исчезло бы. 

[.line-through]##Некоторое зло все же остаётся реальным и порождённым Богом. Это то зло, которое является результатом Божьего наказания за наши грехи. Однако не Бог является исходной причиной этого зла, а человеческий грех. ##

Человеческий грех, реальное зло, происходит не от Бога, а от свободных действий человека. Верно, что Бог даровал людям свободу воли, выбор между праведной и греховной жизнью. Но не Бог является причиной неправильного использования свободы воли, плохих действий. 

На этом завершаем рассмотрение учения Фомы Аквинского, крупнейшей фигуры зрелой схоластики, главного философа Римско-католической церкви, который гармонически синтезировал аристотелизм и христианство.

[glossary]
== Словарь терминов

[[neoplatonism]]Неоплатинизм::
    Ветвь философии Платонизма, которая появилась во втором веке нашей эры на фоне эллинистической философии и религии.

