= Роль технического творчества в становлении опытно-экспериментальной науки

Учёные эпохи Возрождения отдавали предпочтение больше эмпирическому познанию, нежели теоретическому. Леонардо да Винчи считал опыт источником достоверности.

Галилей ввёл два метода экспериментального исследования природы:

1. аналитический - прогнозирование чувственного опыта посредством математики;
2. синтетический - выработка теоретических схем на базе опытного материала.

Ф. Бэкон выступал против схоластики и в "Новом Органоне" выразил недоверие к дедуктивному методу Аристотеля, назвав его "идолом". Вместо этого он предлагает опытно индуктивный метод, обобщение опытных данных.

Эмпиризм - направление в теории познания, признающее чувственный опыт источником знаний, и считающее, что содержание знания может быть представлено либо как описание этого опыта, либо сведено к нему cite:[ogorodnikov].

Рационализм - философское направление, абсолютизирующее рациональные методы, отвергающее чувственный опыт в качестве необходимого основания всякого познания.

Эмпиризм близок к теоретической науке, следовательно, эмпирическая наука есть теоретическая наука. Практика есть творчество. Таким образом, практическое творчество лежит в основе опытной науки.


